---
abstract: unknown
author:
  - unknown
build_requires:
  ExtUtils::MakeMaker: '0'
  ExtUtils::CppGuess: "0.15"
configure_requires:
  ExtUtils::MakeMaker: '6.52'
  ExtUtils::CppGuess: "0.15"
dynamic_config: 1
generated_by: 'ExtUtils::MakeMaker version 7.34, CPAN::Meta::Converter version 2.150001'
license: unknown
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: '1.4'
name: JSON-SIMD
no_index:
  directory:
    - t
    - inc
requires:
  Types::Serialiser: '0'
  common::sense: '0'
resources:
  bugtracker: https://github.com/pjuhasz/JSON-SIMD/issues
  license: http://dev.perl.org/licenses/
  repository: https://github.com/pjuhasz/JSON-SIMD
version: '1.03'
